apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: 'jenkins-test-app'
  description: 'Jenkins Test Application'
  annotations:
    jenkins.io/job-full-name: 'jenkins-test/test-pipeline'
    backstage.io/kubernetes-id: 'jenkins-test'
spec:
  type: service
  lifecycle: experimental
  owner: user:default/backstage-admin
  system: jenkins-system
  dependsOn:
    - resource:jenkins-demo-pipeline