apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: testflask-db
  title: MySQL Database for testflask
  description: MySQL is a powerful, open source object-relational database system.
  links:
    - url: https://www.postgresql.org
      title: PostgreSQL website
      icon: web
    - url: https://postgresql.org/docs
      title: PostgreSQL Documentation
      icon: web
spec:
  type: database
  lifecycle: experimental
  owner: user:default/backstage-admin
  system: testflask-system