apiVersion: rhdh.redhat.com/v1alpha1
kind: Backstage
metadata:
  name: developer-hub
  namespace: ${NAMESPACE}
spec:
  application:
    dynamicPluginsConfigMapName: dynamic-plugins-rhdh
    appConfig:
      configMaps:
       - key: app-config-rhdh.yaml
         name: app-config-rhdh
      mountPath: /opt/app-root/src
    extraFiles:
      mountPath: /opt/app-root/src
      configMaps:
        - name: rbac-policy
          key: rbac-policy.csv
    extraEnvs:
      envs:
        - name: NODE_TLS_REJECT_UNAUTHORIZED
          value: '0'
        - name: LOG_LEVEL
          value: debug
      secrets:
        - name: backstage-sa-secret
        - name: backstage-sso-secret
    replicas: 1
    route:
      enabled: true
  database:
    enableLocalDb: true
  upstream:
    backstage:
      extraAppConfig:
        - configMapRef: app-config-rhdh
          filename: app-config-rhdh.yaml
      extraEnvVars:
        - name: NODE_TLS_REJECT_UNAUTHORIZED
          value: '0'
        - name: LOG_LEVEL
          value: debug
      extraEnvVarsSecrets:
        - backstage-sso-secret
        - backstage-sa-secret
      extraVolumeMounts:
        - mountPath: /opt/app-root/src/rbac
          name: rbac-policy
      extraVolumes:
        - name: rbac-policy
          configMap:
            defaultMode: 420
            name: rbac-policy
            optional: true