apiVersion: rhdh.redhat.com/v1alpha1
kind: Backstage
metadata:
  name: ${BACKSTAGE_CR_NAME}
  namespace: ${NAMESPACE}
spec:
  application:
    route:
      enabled: true
      subdomain: ${BACKSTAGE_CR_NAME}-developer-hub-${NAMESPACE}
    dynamicPluginsConfigMapName: dynamic-plugins-rhdh
    appConfig:
      configMaps:
       - key: app-config-rhdh.yaml
         name: app-config-rhdh
      mountPath: /opt/app-root/src
    extraFiles:
      mountPath: /opt/app-root/src
      configMaps:
        - name: rbac-policy
          key: rbac-policy.csv
    extraEnvs:
      envs:
        - name: NODE_TLS_REJECT_UNAUTHORIZED
          value: '0'
        - name: LOG_LEVEL
          value: debug
      secrets:
        - name: backstage-sa-secret
        - name: backstage-sso-secret
    replicas: 1
  database:
    enableLocalDb: true
