apiVersion: keycloak.org/v1alpha1
kind: KeycloakUser
metadata:
  name: backstage-admin-user
  namespace: ${NAMESPACE}
spec:
  user:
    username: "admin"
    email: "admin@test.com"
    enabled: True
    emailVerified: True
    credentials:
      - type: "password"
        value: "test"
        temporary: false
    realmRoles:
      - "offline_access"
      - "uma_authorization"
      - "user"
  realmSelector:
    matchLabels:
      app: sso-backstage-sample