apiVersion: keycloak.org/v1alpha1
kind: KeycloakUser
metadata:
  name: backstage-user1
  namespace: ${SSO_NAMESPACE}
spec:
  user:
    username: "backstage-user1"
    email: "backstage-user1@test.com"
    enabled: True
    emailVerified: True
    credentials:
      - type: "password"
        value: "test"
        temporary: false
    realmRoles:
      - "offline_access"
      - "uma_authorization"
      - "user"
  realmSelector:
    matchLabels:
      app: sso-backstage-sample
#Username must be set to email due to bug https://issues.redhat.com/browse/RHIDP-2272