apiVersion: keycloak.org/v1alpha1
kind: KeycloakClient
metadata:
  name: backstage-tgm
  namespace: ${SSO_NAMESPACE}
  labels:
    app: sso-backstage-sample
spec:
  serviceAccountRealmRoles:
    - "priv-client"
  client:
    clientId: backstage
    name: backstage
    secret: ${BACKSTAGE_CLIENT_SECRET}
    directAccessGrantsEnabled: true
    implicitFlowEnabled: true
    publicClient: false
    enabled: true
    bearerOnly: false
    consentRequired: false
    standardFlowEnabled: true
    serviceAccountsEnabled: true
    fullScopeAllowed: true
    clientAuthenticatorType: "client-secret"
    attributes:
      saml.multivalued.roles: "false"
      saml.force.post.binding: "false"
      frontchannel.logout.session.required: "false"
      oauth2.device.authorization.grant.enabled: "false"
      backchannel.logout.revoke.offline.tokens: "false"
      saml.server.signature.keyinfo.ext: "false"
      use.refresh.tokens: "true"
      oidc.ciba.grant.enabled: "false"
      backchannel.logout.session.required: "true"
      client_credentials.use_refresh_token: "false"
      saml.client.signature: "false"
      require.pushed.authorization.requests: "false"
      saml.allow.ecp.flow: "false"
      saml.assertion.signature: "false"
      id.token.as.detached.signature: "false"
      saml.encrypt: "false"
      saml.server.signature: "false"
      exclude.session.state.from.auth.response: "false"
      saml.artifact.binding: "false"
      saml_force_name_id_format: "false"
      tls.client.certificate.bound.access.tokens: "false"
      saml.authnstatement: "false"
      display.on.consent.screen: "false"
      token.response.type.bearer.lower-case: "false"
    defaultClientScopes:
      - "web-origins"
      - "profile"
      - "email"
      - "roles"
      - "address"
      - "phone"
      - "offline_access"
    redirectUris: 
      - https://developer-hub-${NAMESPACE}.${BASEDOMAIN}/api/auth/oidc/handler/frame
    protocolMappers:
    - name: backstage-uid
      protocol: openid-connect
      protocolMapper: "oidc-usermodel-property-mapper"
      consentRequired: false
      id: "bee5f236-19a6-4a59-ab14-48b3926de6ca"
      config:
        "userinfo.token.claim": "true"
        "user.attribute": "username"
        "id.token.claim": "true"
        "access.token.claim": "true"
        "claim.name": "sub"
        "jsonType.label": "String"
  realmSelector:
    matchLabels:
      app: sso-backstage-sample
