kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: rhdh-topology-plugin
rules:
  # Base for Kubernetes plugin
  - apiGroups:
      - ''
    resources:
      - pods/log
      - pods
      - services
      - configmaps
      - resourcequotas
      - limitranges
    verbs:
      - get
      - watch
      - list

