kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: rhdh-topology-plugin
rules:
  - verbs:
      - get
      - watch
      - list
    apiGroups:
      - '*'
    resources:
      - pods/log
      - pods
      - services
      - configmaps
      - resourcequotas
      - limitranges
      - deployments
      - taskruns
      - pipelineruns
      - cronjobs
      - jobs
      - replicasets
      - daemonsets
      - routes
      - statefulsets
      - ingresses
      - horizontalpodautoscalers

