kind: ConfigMap
apiVersion: v1
metadata:
  name: rbac-policy
  namespace: ${NAMESPACE}
data:
  rbac-policy.csv: |
    p, role:default/catalog_admin, catalog-entity, read, update, delete
    p, role:default/catalog_admin, catalog.entity.read, read
    p, role:default/catalog_admin, catalog.entity.refresh, update
    p, role:default/catalog_admin, catalog.entity.create, create
    p, role:default/catalog_admin, catalog.entity.delete, delete

    p, role:default/catalog_admin, catalog.location.read, read
    p, role:default/catalog_admin, catalog.location.create, create
    p, role:default/catalog_admin, catalog.location.delete, delete

    p, role:default/catalog_reader, catalog.location.read, read
    p, role:default/catalog_reader, catalog.entity.read, read

    p, role:default/scaffolder_admin, scaffolder.template, read
    p, role:default/scaffolder_admin, scaffolder.template.parameter.read, read
    p, role:default/scaffolder_admin, scaffolder.template.step.read, read
    p, role:default/scaffolder_admin, scaffolder.action.execute, use
    p, role:default/scaffolder_admin, scaffolder.action, use

    p, role:default/rbac_admin, policy.entity.read, read
    p, role:default/rbac_admin, policy.entity.create, create
    p, role:default/rbac_admin, policy.entity.update, update
    p, role:default/rbac_admin, policy.entity.delete, delete
    p, role:default/rbac_admin, kubernetes.proxy, use
   

    g, user:default/admin, role:default/rbac_admin
    g, user:default/admin, role:default/catalog_admin
    g, user:default/admin, role:default/scaffolder_admin
    g, user:default/user1, role:default/catalog_admin
    g, user:default/:id, role:default/catalog_reader