kind: ConfigMap
apiVersion: v1
metadata:
  name: rbac-policy
  namespace: ${NAMESPACE}
data:
  rbac-policy.csv: |
    p, role:default/catalog_admin, catalog-entity, read, allow
    p, role:default/catalog_admin, catalog.entity.read, read, allow
    p, role:default/catalog_admin, catalog.entity.refresh, update, allow
    p, role:default/catalog_admin, catalog.entity.create, create, allow
    p, role:default/catalog_admin, catalog.entity.delete, delete, allow

    p, role:default/catalog_admin, catalog.location.read, read, allow
    p, role:default/catalog_admin, catalog.location.create, create, allow
    p, role:default/catalog_admin, catalog.location.delete, delete, allow

    p, role:default/catalog_reader, catalog.location.read, read, allow
    p, role:default/catalog_reader, catalog.entity.read, read, allow

    p, role:default/scaffolder_admin, scaffolder.template, read, allow
    p, role:default/scaffolder_admin, scaffolder.template.parameter.read, read, allow
    p, role:default/scaffolder_admin, scaffolder.template.step.read, read, allow
    p, role:default/scaffolder_admin, scaffolder.action.execute, use, allow
    p, role:default/scaffolder_admin, scaffolder.action, use, allow

    p, role:default/rbac_admin, catalog-entity, read, allow
    p, role:default/rbac_admin, policy.entity.read, read, allow
    p, role:default/rbac_admin, policy.entity.create, create, allow
    p, role:default/rbac_admin, policy.entity.update, update, allow
    p, role:default/rbac_admin, policy.entity.delete, delete, allow
    p, role:default/rbac_admin, kubernetes.proxy, use, allow

    g, group:default/backstage-admin, role:default/rbac_admin
    g, group:default/backstage-admin, role:default/catalog_admin
    g, group:default/backstage-admin, role:default/scaffolder_admin
    g, group:default/backstage-catalog-admin, role:default/catalog_admin
    g, group:default/backstage-user, role:default/catalog_reader
