global:
  dynamic:
    plugins:
      - disabled: false
        package: ./dynamic-plugins/dist/janus-idp-backstage-plugin-rbac 
      - disabled: false
        package: ./dynamic-plugins/dist/backstage-plugin-kubernetes
      - disabled: false
        package: ./dynamic-plugins/dist/backstage-plugin-kubernetes-backend-dynamic
      - disabled: false
        package: ./dynamic-plugins/dist/janus-idp-backstage-plugin-topology
      - disabled: false
        package: >-
          ./dynamic-plugins/dist/janus-idp-backstage-plugin-keycloak-backend-dynamic
upstream:
  backstage:
    extraAppConfig:
      - configMapRef: app-config-rhdh
        filename: app-config-rhdh.yaml
    extraEnvVars:
      - name: NODE_TLS_REJECT_UNAUTHORIZED
        value: '0'
    extraEnvVarsSecrets:
      - backstage-sso-secret
      - backstage-sa-secret
    extraVolumeMounts:
      - mountPath: /opt/app-root/src/rbac
        name: rbac-policy
    extraVolumes:
      - name: rbac-policy
        configMap:
          defaultMode: 420
          name: rbac-policy
          optional: true
