pipeline {

    agent {
      kubernetes {
        cloud "openshift"
        containerTemplate {
          name "jnlp"
          image "registry.redhat.io/openshift4/ose-jenkins-agent-maven@sha256:0db8402dc42967436168e045c097709783deafdc9f97e41172bd35344a500138"  
          resourceRequestMemory "500Mi"
          resourceLimitMemory "500Mi"
          resourceRequestCpu "300m"
          resourceLimitCpu "300m"
          alwaysPullImage "True"
        }
      }
    }

    stages {
        stage('build') {
            steps {
                sh 'mvn --version'
            }
        }
    }
}