pipeline {

    agent {
      kubernetes {
        cloud "openshift"
        containerTemplate {
          name "jnlp"
          image "registry.redhat.io/openshift3/jenkins-agent-maven-36-rhel7@sha256:f34e5808e759a269872676cf5ba658168a4acbb4bb41790e51b01ffb65124d1d"  
          resourceRequestMemory "500Mi"
          resourceLimitMemory "500Mi"
          resourceRequestCpu "300m"
          resourceLimitCpu "300m"
          alwaysPullImage "True"
        }
      }
    }

    stages {
        stage('build') {
            steps {
                sh 'mvn --version'
            }
        }
    }
}