kind: Secret
apiVersion: v1
metadata:
  name: jenkins-backstage-secret
  namespace: ${NAMESPACE}
stringData:
  JENKINS_URL: https://${JENKINS_ROUTE}
  JENKINS_USERNAME: ${JENKINS_USERNAME}
  JENKINS_TOKEN: ${JENKINS_API_TOKEN}
type: Opaque


